In [1]:
from fastai import *
from fastai.vision import *

In [2]:
class CustomImageItemList(ImageList):
    def custom_label(self,df, **kwargs)->'LabelList':
        """Custom Labels from path"""
        file_names=np.vectorize(lambda files: str(files).split('/')[-1][:-4])
        get_labels=lambda x: df.loc[x,'lesion']
        #self.items is an np array of PosixPath objects with each image path
        labels= get_labels(file_names(self.items))
        y = CategoryList(items=labels)
        res = self._label_list(x=self,y=y)
        return res

In [3]:
learn = load_learner('models/')

In [19]:
img = open_image("../../micky.jpg")

In [33]:
m = learn.predict(img)

In [41]:
print(m[2])

tensor([3.4240e-07, 3.9013e-05, 2.1591e-05, 3.7378e-06, 9.9957e-01, 1.9894e-04,
        1.6658e-04])


In [36]:
torch.max(probs)

tensor(4)

In [43]:
sort = torch.sort(m[2])

In [44]:
sort

(tensor([3.4240e-07, 3.7378e-06, 2.1591e-05, 3.9013e-05, 1.6658e-04, 1.9894e-04,
         9.9957e-01]), tensor([0, 3, 2, 1, 6, 5, 4]))

In [25]:
sort[:3]

(tensor(4), tensor(0))

In [45]:
print(sort[0][:3])
print(sort[1][:3])

tensor([3.4240e-07, 3.7378e-06, 2.1591e-05])
tensor([0, 3, 2])


In [22]:
torch.min(probs)

tensor(3.6623e-05)

In [15]:
m = nn.Softmax()

In [16]:
m(probs)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([0.1216, 0.1207, 0.2189, 0.1206, 0.1733, 0.1244, 0.1206])